{% set version = "1.7.2" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://github.com/apache/orc/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4e27139bb91e93801c38744c767d46dcd164fa9e87ff08e05ca0868f7e813d2e
  patches:
    # ORC builds by default with -Werror but some dependencies omit warnings.
    # This deactivates -Werror
    - 0001-Deactivate-aggressive-failures-on-warnings.patch
    - 0002-Don-t-force-orc-to-be-a-static-library-let-end-user-.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("orc", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja       # [unix]
    # `protoc` is also used for building
    - libprotobuf {{ protobuf }}
    - cmake {{ cmake }}
  host:
    - zlib  {{ zlib }}
    - snappy
    - libprotobuf {{ protobuf }}
    - lz4-c
    - zstd  {{ zstd }}

test:
  commands:
    - test -f $PREFIX/lib/liborc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/orc/Common.hh   # [unix]

about:
  home: http://github.com/apache/orc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ libraries for Apache ORC
  description: C++ libraries for Apache ORC

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
